jobs:
  build_aisha:
    name: Build Aisha extension
    runs-on: ubuntu-latest
    env:
      CI_CHUNK_SIZE: '1'  # Set this to an appropriate value
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true

      - name: Build Aisha extension
        run: |
          ./gradlew :src:en:aisha:assembleDebug

      - name: Upload built Aisha extension
        uses: actions/upload-artifact@v3
        with:
          name: aisha-extension
          path: src/en/aisha/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
